export const listUnits = [
  { value: 'Blatt', display: 'Blatt' },
  { value: 'Deziliter', display: 'Deziliter' },
  { value: 'Dose', display: 'Dose' },
  { value: 'Esslöffel', display: 'Esslöffel' },
  { value: 'Flasche', display: 'Flasche' },
  { value: 'Gramm', display: 'Gramm' },
  { value: 'Glas', display: 'Glas' },
  { value: 'Kilogramm', display: 'Kilogramm' },
  { value: 'Kugel', display: 'Kugel' },
  { value: 'Liter', display: 'Liter' },
  { value: 'Milligramm', display: 'Milligramm' },
  { value: 'Milliliter', display: 'Milliliter' },
  { value: 'Packung', display: 'Packung' },
  { value: 'Portion', display: 'Portion' },
  { value: 'Prise', display: 'Prise' },
  { value: 'Riegel', display: 'Riegel' },
  { value: 'Scheibe', display: 'Scheibe' },
  { value: 'Stange', display: 'Stange' },
  { value: 'Stück', display: 'Stück' },
  { value: 'Tasse', display: 'Tasse' },
  { value: 'Teelöffel', display: 'Teelöffel' },
  { value: 'Würfel', display: 'Würfel' }
];
